server:
  port: 5000
spring:
  r2dbc:
    url: r2dbc:mysql://pos-tendering-db.cpymyqaiwd9e.us-east-2.rds.amazonaws.com:3306/IntellijIdea
    username: admin
    password: test1234

  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.mysql: INFO
