spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/IntellijIdea
    username: root
    password: test1234

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG
